[project]
name = "advanced-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ravikn2017", email = "ravikn2007@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.0",
    "langchain-arxiv-retriever>=1.0.0",
    "langchain-community",
    "langchain-core",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.0",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.11",
    "pillow",
    "python-dotenv>=1.2.3",
]

[project.scripts]
advanced-langgraph = "advanced_langgraph:main"

[tool.basedpyright]
venvPath = "."
venv = ".venv"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
